import { NextRequest, NextResponse } from "next/server";
import { checkRateLimit, identifierFromRequest } from "@/lib/rateLimit";

const isDev = process.env.NODE_ENV !== "production";

function buildCsp(nonce: string) {
  // In dev, Next's hot-reload needs inline scripts + eval() (react-refresh).
  // In production, every script — ours and Next's own hydration scripts —
  // must carry this request's nonce. 'strict-dynamic' lets a nonce'd script
  // load further scripts (Next's chunk loader needs this), and browsers
  // that support it ignore the host-based fallbacks, so older browsers
  // still get a (looser but safe) same-origin fallback via 'self'.
  const scriptSrc = isDev
    ? "script-src 'self' 'unsafe-inline' 'unsafe-eval'"
    : `script-src 'self' 'nonce-${nonce}' 'strict-dynamic'`;

  return [
    "default-src 'self'",
    "img-src 'self' https://avatars.githubusercontent.com data:",
    "style-src 'self' 'unsafe-inline'",
    scriptSrc,
    "connect-src 'self' https://api.github.com https://github.com",
    "frame-ancestors 'none'",
    "base-uri 'self'",
    "form-action 'self'"
  ].join("; ");
}

export async function middleware(req: NextRequest) {
  // A lighter, IP-based limit specifically on the OAuth endpoints, so the
  // sign-in flow itself can't be used to hammer GitHub or brute-force
  // callback params. The per-user limit in /api/contributions handles the
  // data endpoint separately.
  if (req.nextUrl.pathname.startsWith("/api/auth")) {
    const identifier = identifierFromRequest(req);
    const { success, reset } = await checkRateLimit(`auth:${identifier}`);
    if (!success) {
      return NextResponse.json(
        { error: "Too many requests. Try again shortly." },
        { status: 429, headers: { "Retry-After": Math.max(0, Math.ceil((reset - Date.now()) / 1000)).toString() } }
      );
    }
  }

  // A fresh random value per request — this is what makes the CSP safe.
  // A hash can only allowlist content that's identical every time; a nonce
  // proves "this script was generated by this exact server response."
  const nonce = btoa(crypto.randomUUID());
  const csp = buildCsp(nonce);

  // Forwarded to Server Components via request headers, so app/layout.tsx
  // can read it and put it on our own inline script tag.
  const requestHeaders = new Headers(req.headers);
  requestHeaders.set("x-nonce", nonce);

  const response = NextResponse.next({ request: { headers: requestHeaders } });
  response.headers.set("Content-Security-Policy", csp);
  return response;
}

export const config = {
  matcher: [
    // Run on everything except static assets and image optimization files —
    // those don't render HTML, so they don't need a CSP or a nonce.
    {
      source: "/((?!_next/static|_next/image|favicon.ico).*)",
      missing: [
        { type: "header", key: "next-router-prefetch" },
        { type: "header", key: "purpose", value: "prefetch" }
      ]
    }
  ]
};
